/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    authors: Author;
    sources: Source;
    media: Media;
    'source-documents': SourceDocument;
    stories: Story;
    companies: Company;
    people: Person;
    institutions: Institution;
    education: Education;
    'company-roles': CompanyRole;
    ownership: Ownership;
    events: Event;
    observations: Observation;
    taxonomy: Taxonomy;
    redirects: Redirect;
    'content-inbox': ContentInbox;
    'content-jobs': ContentJob;
    'claim-evidence': ClaimEvidence;
    'generated-assets': GeneratedAsset;
    'review-decisions': ReviewDecision;
    'prompt-templates': PromptTemplate;
    'migration-records': MigrationRecord;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'source-documents': SourceDocumentsSelect<false> | SourceDocumentsSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    institutions: InstitutionsSelect<false> | InstitutionsSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    'company-roles': CompanyRolesSelect<false> | CompanyRolesSelect<true>;
    ownership: OwnershipSelect<false> | OwnershipSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    observations: ObservationsSelect<false> | ObservationsSelect<true>;
    taxonomy: TaxonomySelect<false> | TaxonomySelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'content-inbox': ContentInboxSelect<false> | ContentInboxSelect<true>;
    'content-jobs': ContentJobsSelect<false> | ContentJobsSelect<true>;
    'claim-evidence': ClaimEvidenceSelect<false> | ClaimEvidenceSelect<true>;
    'generated-assets': GeneratedAssetsSelect<false> | GeneratedAssetsSelect<true>;
    'review-decisions': ReviewDecisionsSelect<false> | ReviewDecisionsSelect<true>;
    'prompt-templates': PromptTemplatesSelect<false> | PromptTemplatesSelect<true>;
    'migration-records': MigrationRecordsSelect<false> | MigrationRecordsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'prepare-content': TaskPrepareContent;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'contributor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  path?: string | null;
  bio?: string | null;
  legacyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  title: string;
  url: string;
  publisher: string;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  evidence?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit: string;
  originalURL?: string | null;
  checksum?: string | null;
  generated?: boolean | null;
  provenance?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  approved?: boolean | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    editorial?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-documents".
 */
export interface SourceDocument {
  id: number;
  title: string;
  checksum?: string | null;
  retentionUntil?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  path: string;
  legacyKey?: string | null;
  legacyStatus?: string | null;
  kind: 'article' | 'ownership' | 'leader' | 'salary' | 'company' | 'page';
  category: string;
  dek: string;
  author?: (number | null) | Author;
  featuredImage?: (number | null) | Media;
  publishedAt?: string | null;
  modifiedAt?: string | null;
  sections?:
    | {
        anchor: string;
        heading: string;
        text: string;
        sourceIds?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortAnswer?: string | null;
  facts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        date: string;
        text: string;
        sourceIds?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  relations?:
    | {
        from: string;
        to: string;
        label: string;
        stake?: number | null;
        id?: string | null;
      }[]
    | null;
  chartMetrics?:
    | {
        label: string;
        value?: number | null;
        currency?: string | null;
        unit: string;
        period: string;
        definition: string;
        basis: 'reported' | 'estimated' | 'calculated';
        geography?: string | null;
        sourceIds:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  sources?: (number | Source)[] | null;
  companies?: (number | Company)[] | null;
  people?: (number | Person)[] | null;
  taxonomy?: (number | Taxonomy)[] | null;
  relatedStories?: (number | Story)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonical?: string | null;
    noindex?: boolean | null;
  };
  legacyHTML?: string | null;
  importChecksum?: string | null;
  sourceJobKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  canonicalKey?: string | null;
  _status?: ('draft' | 'published') | null;
  vertical: string;
  legalEntity?: string | null;
  website?: string | null;
  description?: string | null;
  profile?: (number | null) | Story;
  observations?: (number | Observation)[] | null;
  sources: (number | Source)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "observations".
 */
export interface Observation {
  id: number;
  name: string;
  canonicalKey?: string | null;
  _status?: ('draft' | 'published') | null;
  label: string;
  value?: number | null;
  currency?: string | null;
  unit: string;
  period: string;
  definition: string;
  basis: 'reported' | 'estimated' | 'calculated';
  geography?: string | null;
  sourceIds:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  display?: string | null;
  company?: (number | null) | Company;
  person?: (number | null) | Person;
  occupation?: string | null;
  seniority?: string | null;
  statistic?: string | null;
  sampleSize?: number | null;
  methodology?: string | null;
  sources: (number | Source)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  canonicalKey?: string | null;
  _status?: ('draft' | 'published') | null;
  biography?: string | null;
  portrait?: (number | null) | Media;
  profile?: (number | null) | Story;
  sources: (number | Source)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomy".
 */
export interface Taxonomy {
  id: number;
  name: string;
  path: string;
  legacyKey?: string | null;
  kind?: ('category' | 'tag') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions".
 */
export interface Institution {
  id: number;
  name: string;
  canonicalKey?: string | null;
  _status?: ('draft' | 'published') | null;
  location?: string | null;
  website?: string | null;
  sources: (number | Source)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: number;
  name: string;
  canonicalKey?: string | null;
  _status?: ('draft' | 'published') | null;
  person?: (number | null) | Person;
  institution?: (number | null) | Institution;
  awardingInstitution?: (number | null) | Institution;
  program?: string | null;
  subject?: string | null;
  start?: string | null;
  end?: string | null;
  graduation?: string | null;
  precision?: ('day' | 'month' | 'year' | 'unknown') | null;
  sources: (number | Source)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-roles".
 */
export interface CompanyRole {
  id: number;
  name: string;
  canonicalKey?: string | null;
  _status?: ('draft' | 'published') | null;
  person?: (number | null) | Person;
  company?: (number | null) | Company;
  roleType?: ('executive' | 'founder' | 'board' | 'investor' | 'partnership') | null;
  start?: string | null;
  end?: string | null;
  sources: (number | Source)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ownership".
 */
export interface Ownership {
  id: number;
  name: string;
  canonicalKey?: string | null;
  _status?: ('draft' | 'published') | null;
  parent?: (number | null) | Company;
  child?: (number | null) | Company;
  stake?: number | null;
  rights?: ('equity' | 'voting' | 'unknown') | null;
  effectiveAt?: string | null;
  sources: (number | Source)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  canonicalKey?: string | null;
  _status?: ('draft' | 'published') | null;
  company?: (number | null) | Company;
  eventType?: string | null;
  effectiveAt?: string | null;
  amount?: number | null;
  currency?: string | null;
  sources: (number | Source)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  reason: string;
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Save the packet, then request preparation. All generated content remains a draft.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-inbox".
 */
export interface ContentInbox {
  id: number;
  name: string;
  workflow: 'leader' | 'salary' | 'ownership' | 'article';
  text?: string | null;
  urls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  documents?: (number | SourceDocument)[] | null;
  referenceImages?: (number | Media)[] | null;
  imageMode?: ('reuse' | 'generate' | 'none') | null;
  allowResearch?: boolean | null;
  target?: (number | null) | Story;
  targetVersion?: string | null;
  proposedPath: string;
  author?: (number | null) | Author;
  /**
   * Queue draft preparation on save.
   */
  prepare?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-jobs".
 */
export interface ContentJob {
  id: number;
  name: string;
  key?: string | null;
  state?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  /**
   * Retry resumes saved stages; cancel stops future stages.
   */
  action?: ('retry' | 'cancel') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claim-evidence".
 */
export interface ClaimEvidence {
  id: number;
  name: string;
  key?: string | null;
  state?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generated-assets".
 */
export interface GeneratedAsset {
  id: number;
  name: string;
  key?: string | null;
  state?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-decisions".
 */
export interface ReviewDecision {
  id: number;
  name: string;
  key?: string | null;
  state?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates".
 */
export interface PromptTemplate {
  id: number;
  name: string;
  key?: string | null;
  state?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-records".
 */
export interface MigrationRecord {
  id: number;
  name: string;
  key?: string | null;
  state?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'prepare-content';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'prepare-content') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'source-documents';
        value: number | SourceDocument;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'institutions';
        value: number | Institution;
      } | null)
    | ({
        relationTo: 'education';
        value: number | Education;
      } | null)
    | ({
        relationTo: 'company-roles';
        value: number | CompanyRole;
      } | null)
    | ({
        relationTo: 'ownership';
        value: number | Ownership;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'observations';
        value: number | Observation;
      } | null)
    | ({
        relationTo: 'taxonomy';
        value: number | Taxonomy;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'content-inbox';
        value: number | ContentInbox;
      } | null)
    | ({
        relationTo: 'content-jobs';
        value: number | ContentJob;
      } | null)
    | ({
        relationTo: 'claim-evidence';
        value: number | ClaimEvidence;
      } | null)
    | ({
        relationTo: 'generated-assets';
        value: number | GeneratedAsset;
      } | null)
    | ({
        relationTo: 'review-decisions';
        value: number | ReviewDecision;
      } | null)
    | ({
        relationTo: 'prompt-templates';
        value: number | PromptTemplate;
      } | null)
    | ({
        relationTo: 'migration-records';
        value: number | MigrationRecord;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  path?: T;
  bio?: T;
  legacyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  publisher?: T;
  publishedAt?: T;
  reviewedAt?: T;
  evidence?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  originalURL?: T;
  checksum?: T;
  generated?: T;
  provenance?: T;
  approved?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        editorial?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-documents_select".
 */
export interface SourceDocumentsSelect<T extends boolean = true> {
  title?: T;
  checksum?: T;
  retentionUntil?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  legacyKey?: T;
  legacyStatus?: T;
  kind?: T;
  category?: T;
  dek?: T;
  author?: T;
  featuredImage?: T;
  publishedAt?: T;
  modifiedAt?: T;
  sections?:
    | T
    | {
        anchor?: T;
        heading?: T;
        text?: T;
        sourceIds?: T;
        id?: T;
      };
  body?: T;
  shortAnswer?: T;
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        date?: T;
        text?: T;
        sourceIds?: T;
        id?: T;
      };
  relations?:
    | T
    | {
        from?: T;
        to?: T;
        label?: T;
        stake?: T;
        id?: T;
      };
  chartMetrics?:
    | T
    | {
        label?: T;
        value?: T;
        currency?: T;
        unit?: T;
        period?: T;
        definition?: T;
        basis?: T;
        geography?: T;
        sourceIds?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  sources?: T;
  companies?: T;
  people?: T;
  taxonomy?: T;
  relatedStories?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noindex?: T;
      };
  legacyHTML?: T;
  importChecksum?: T;
  sourceJobKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  canonicalKey?: T;
  _status?: T;
  vertical?: T;
  legalEntity?: T;
  website?: T;
  description?: T;
  profile?: T;
  observations?: T;
  sources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  canonicalKey?: T;
  _status?: T;
  biography?: T;
  portrait?: T;
  profile?: T;
  sources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions_select".
 */
export interface InstitutionsSelect<T extends boolean = true> {
  name?: T;
  canonicalKey?: T;
  _status?: T;
  location?: T;
  website?: T;
  sources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  name?: T;
  canonicalKey?: T;
  _status?: T;
  person?: T;
  institution?: T;
  awardingInstitution?: T;
  program?: T;
  subject?: T;
  start?: T;
  end?: T;
  graduation?: T;
  precision?: T;
  sources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-roles_select".
 */
export interface CompanyRolesSelect<T extends boolean = true> {
  name?: T;
  canonicalKey?: T;
  _status?: T;
  person?: T;
  company?: T;
  roleType?: T;
  start?: T;
  end?: T;
  sources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ownership_select".
 */
export interface OwnershipSelect<T extends boolean = true> {
  name?: T;
  canonicalKey?: T;
  _status?: T;
  parent?: T;
  child?: T;
  stake?: T;
  rights?: T;
  effectiveAt?: T;
  sources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  canonicalKey?: T;
  _status?: T;
  company?: T;
  eventType?: T;
  effectiveAt?: T;
  amount?: T;
  currency?: T;
  sources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "observations_select".
 */
export interface ObservationsSelect<T extends boolean = true> {
  name?: T;
  canonicalKey?: T;
  _status?: T;
  label?: T;
  value?: T;
  currency?: T;
  unit?: T;
  period?: T;
  definition?: T;
  basis?: T;
  geography?: T;
  sourceIds?: T;
  display?: T;
  company?: T;
  person?: T;
  occupation?: T;
  seniority?: T;
  statistic?: T;
  sampleSize?: T;
  methodology?: T;
  sources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomy_select".
 */
export interface TaxonomySelect<T extends boolean = true> {
  name?: T;
  path?: T;
  legacyKey?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  reason?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-inbox_select".
 */
export interface ContentInboxSelect<T extends boolean = true> {
  name?: T;
  workflow?: T;
  text?: T;
  urls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  documents?: T;
  referenceImages?: T;
  imageMode?: T;
  allowResearch?: T;
  target?: T;
  targetVersion?: T;
  proposedPath?: T;
  author?: T;
  prepare?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-jobs_select".
 */
export interface ContentJobsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  state?: T;
  data?: T;
  error?: T;
  action?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claim-evidence_select".
 */
export interface ClaimEvidenceSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  state?: T;
  data?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generated-assets_select".
 */
export interface GeneratedAssetsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  state?: T;
  data?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-decisions_select".
 */
export interface ReviewDecisionsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  state?: T;
  data?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates_select".
 */
export interface PromptTemplatesSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  state?: T;
  data?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-records_select".
 */
export interface MigrationRecordsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  state?: T;
  data?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  featuredStories?: (number | Story)[] | null;
  heroTitle?: string | null;
  heroDescription?: string | null;
  newsletterURL?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  featuredStories?: T;
  heroTitle?: T;
  heroDescription?: T;
  newsletterURL?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPrepare-content".
 */
export interface TaskPrepareContent {
  input: {
    jobID: string;
  };
  output: {
    recordID?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}