from pathlib import Path
from html import escape as esc
import re,json
R=Path(__file__).resolve().parents[1];D=R/'dist'
d=json.loads((D/'data/ai-companies.json').read_text());cs=d['companies'];e=lambda x:esc(str(x),quote=True)
verticals=sorted(set(c['vertical'] for c in cs))
base=(D/'article.html').read_text();header=re.search(r'<header class="site-header.*?</header>',base,re.S).group()
header=header.replace('</nav>','<a href="./ai-companies.html" aria-current="page">AI Tracker</a></nav>') if 'ai-companies.html' not in header else header.replace('href="./ai-companies.html"','href="./ai-companies.html" aria-current="page"')
brief=re.search(r'<section class="page-width brief article-brief".*?</section>',base,re.S).group().replace('id="article-brief-form"','id="tracker-brief-form"').replace('id="article-form-message"','id="tracker-form-message"')
rows=[]
for c in cs:
 o=c['observations'][0];id=c['id'];age='Earlier snapshot' if o['asOf']<'2026-07' else ''
 ownership=f'<a href="{e(c["ownershipUrl"])}">Read the ownership story</a>' if c['ownershipUrl'] else ''
 profile=f'<a href="{e(c["profileUrl"])}">Company profile</a>' if c['profileUrl'] else ''
 rows.append(f'''<tbody data-company="{id}"><tr class="company-data-row"><th scope="row" data-label="Company"><button class="company-expand" aria-expanded="false" aria-controls="detail-{id}"><span>{e(c['name'])}</span><span class="expand-symbol" aria-hidden="true">+</span></button><span class="company-description">{e(c['description'])}</span></th><td data-label="Vertical"><span class="vertical-tag">{e(c['vertical'])}</span></td><td class="metric-cell" data-label="Est. ARR / run rate"><strong>{e(o['display'])}</strong><small>{e(o['metric'])}</small></td><td data-label="As of"><time datetime="{o['asOf']}">{o['asOfLabel']}</time>{f'<small class="earlier">{age}</small>' if age else ''}</td><td data-label="Evidence"><span class="basis-label">{e(o['basis'])}</span><a class="source-link" href="{e(o['source']['url'])}" target="_blank" rel="noopener">{e(o['source']['publisher'])}<span class="sr-only"> source for {e(c['name'])} (opens new tab)</span></a></td></tr><tr class="company-detail" id="detail-{id}" hidden><td colspan="5"><div class="detail-grid"><div><span class="eyebrow">READING THIS FIGURE</span><p>{e(o['note'])}</p><div class="detail-links">{ownership}{profile}</div></div><dl><dt>Metric</dt><dd>{e(o['metric'])}</dd><dt>Currency</dt><dd>USD</dd><dt>Source published</dt><dd>{e(o['source']['publishedAt'] or 'Undated profile')}</dd><dt>Checked</dt><dd>October 4, 2026</dd></dl></div></td></tr></tbody>''')
chips=''.join(f'<button type="button" data-vertical="{e(v)}" aria-pressed="{str(v=="All").lower()}">{e(v)}<span>{len(cs) if v=="All" else sum(c["vertical"]==v for c in cs)}</span></button>' for v in ['All']+verticals)
url='https://visionary-talks-editorial-concept.omerlewins.chatgpt.site/ai-companies.html'
schema={'@context':'https://schema.org','@type':'CollectionPage','name':'AI companies tracker','description':'Dated ARR and annualized revenue observations by company and vertical.','url':url,'dateModified':d['reviewedAt'],'publisher':{'@type':'Organization','name':'Visionary Talks'}}
html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Companies Tracker: Estimated ARR &amp; Verticals | Visionary Talks</title><meta name="description" content="Explore ten AI companies by vertical, estimated ARR and annualized revenue, with dated sources and evidence notes."><meta name="robots" content="noindex,follow"><link rel="canonical" href="{url}"><meta property="og:type" content="website"><meta property="og:title" content="AI companies tracker | Visionary Talks"><meta property="og:description" content="The businesses behind the AI boom, in numbers."><meta property="og:url" content="{url}"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="./styles.css"><link rel="stylesheet" href="./article.css"><link rel="stylesheet" href="./ai-tracker.css"><script type="application/ld+json">{json.dumps(schema)}</script></head><body class="tracker-page magazine-home"><a class="skip-link" href="#company-table">Skip to company table</a>{header}<main><div class="page-width"><nav class="tracker-breadcrumb" aria-label="Breadcrumb"><a href="./index.html">Home</a><span>/</span><span aria-current="page">AI companies tracker</span></nav><section class="tracker-intro"><div><span class="eyebrow">THE VISIONARY INDEX / AI BUSINESS</span><h1>AI companies,<br><em>in numbers.</em></h1><p>The businesses behind the AI boom. Explore their verticals, revenue estimates, and the evidence behind each figure.</p></div><aside class="tracker-edition"><span>THE COMPANY TRACKER</span><b>{len(cs):02d}<span>companies</span></b><div><strong>{len(verticals)}</strong><span>verticals covered</span></div><p>Editorial snapshot<br>Reviewed October 4, 2026</p></aside></section>
<div class="tracker-context"><p><b>ARR and run rate are different.</b> Each row names the source’s metric. Figures are USD snapshots from different dates—not a like-for-like revenue ranking.</p><a href="#tracker-methodology">How we track the numbers</a></div>
<section class="tracker-workspace" aria-labelledby="tracker-table-title"><div class="tracker-toolbar"><div class="tracker-search"><label for="company-search">Find a company</label><input id="company-search" type="search" placeholder="Search companies or verticals" autocomplete="off"></div><div><label for="metric-filter">Metric</label><select id="metric-filter"><option value="All">ARR + annualized revenue</option><option value="ARR">ARR only</option><option value="Annualized revenue">Annualized revenue only</option></select></div><div><label for="company-sort">Sort by</label><select id="company-sort"><option value="desc">Reported figure: high to low</option><option value="asc">Reported figure: low to high</option><option value="recent">Most recent observation</option><option value="name">Company: A–Z</option></select></div></div><div class="tracker-filters" role="group" aria-label="Filter by vertical">{chips}</div><div class="tracker-table-heading"><h2 id="tracker-table-title">The companies</h2><p id="tracker-count" role="status" aria-live="polite">Showing {len(cs)} of {len(cs)} companies</p><button class="clear-filters" type="button" id="clear-filters">Reset filters</button></div><p class="table-instruction">Select a company name for source notes and related ownership coverage.</p><table class="ai-company-table" id="company-table"><caption class="sr-only">AI companies with estimated ARR or annualized revenue, vertical, observation date, and source.</caption><thead><tr><th scope="col">Company</th><th scope="col">Vertical</th><th scope="col">Est. ARR / run rate</th><th scope="col">As of</th><th scope="col">Evidence &amp; source</th></tr></thead>{''.join(rows)}</table><div class="tracker-empty" id="tracker-empty" hidden><h3>No companies match these filters.</h3><p>Try another name or clear the filters to see the full index.</p><button type="button" id="empty-reset">Show all companies</button></div><noscript><p class="tracker-noscript">JavaScript is needed for filters and expandable notes. The full table and source links remain available.</p></noscript><p class="tracker-footnote">~ Approximate or estimated · &gt; Reported to exceed · Earlier snapshot: dated before July 2026. Sorting uses the displayed estimate or threshold, not a precise ranking.</p></section>
<section class="tracker-methodology" id="tracker-methodology"><div><span class="eyebrow">A NOTE ON THE NUMBERS</span><h2>Read the evidence.<br>Then read the number.</h2></div><div><details open><summary>What do ARR and annualized revenue mean?</summary><p>ARR describes the annual recurring value of a revenue base. Annualized revenue projects a shorter period over a year and may include usage-based sales. We preserve the metric identified by each source. Neither is the same as audited full-year revenue.</p></details><details><summary>Where do these figures come from?</summary><p>“Company disclosed” means a company announcement. “Reported” means editorial reporting, sometimes citing a founder or an unnamed source. “Estimated” means a third-party research estimate. These labels describe provenance, not an audit or guarantee. Click any source to inspect it.</p></details><details><summary>How current and comparable are the numbers?</summary><p>This is a manually reviewed October 4, 2026 snapshot of selected observations, not a live feed or a complete market census. The “As of” column is the metric’s observation month where available; notes identify disclosure dates when the exact measurement date is unknown. Accounting, scope, and definitions differ. We do not sum the rows or calculate market share.</p></details><details><summary>How are verticals assigned?</summary><p>Verticals are Visionary Talks editorial categories based on the company’s principal product. A company can span several markets; this index assigns one primary category to make it easier to browse. Subsidiary figures refer to that business, not its parent group.</p></details></div></section>
<section class="tracker-next"><span class="eyebrow">GO BEHIND THE NUMBER</span><h2>Revenue is one part of the story.</h2><div><a href="./who-owns-cursor.html"><span>OWNERSHIP</span><h3>Who owns Cursor?</h3><p>Follow the company behind the code editor.</p></a><a href="./index.html#people"><span>PEOPLE</span><h3>Meet the leaders.</h3><p>The people shaping the next chapter of business.</p></a><a href="./index.html#salary-tracker"><span>CAREERS &amp; DATA</span><h3>What does AI work pay?</h3><p>Explore the AI salaries tracker.</p></a></div></section></div>{brief}</main><footer class="footer"><div class="page-width"><div class="footer-top"><div><a href="./index.html" class="footer-logo">VISIONARY TALKS</a><p>Companies. Money. Careers.</p></div><div class="footer-links"><a href="./index.html#ownership">Ownership</a><a href="./index.html#people">Leaders</a><a href="#tracker-methodology">Methodology</a></div></div><div class="footer-bottom"><span>© 2026 Visionary Talks · Design preview</span><a href="#top">Back to top</a></div></div></footer><script id="tracker-data" type="application/json">{json.dumps(d).replace('<','\\u003c')}</script><script src="./ai-tracker-core.js"></script><script src="./ai-tracker.js"></script></body></html>'''
(D/'ai-companies.html').write_text(html)
# The home preview uses this same source data.
preview=[]
for id in ['base44','lovable','anysphere','elevenlabs']:
 c=next(c for c in cs if c['id']==id);o=c['observations'][0]
 preview.append(f'<tr><th scope="row"><a href="./ai-companies.html?company={e(c["name"])}">{e(c["name"])}</a></th><td>{e(c["vertical"])}</td><td><b>{e(o["display"])}</b><small>{e(o["metric"])} · {e(o["asOfLabel"])}</small></td></tr>')
homeblock=f'''<section class="section home-ai-index" id="ai-companies" aria-labelledby="home-ai-title"><div class="home-ai-intro"><span class="eyebrow">THE VISIONARY INDEX / AI COMPANIES</span><h2 id="home-ai-title">Behind the hype.<br><em>Inside the business.</em></h2><p>From app builders to AI models. Track the companies, their verticals, and the revenue figures behind the headlines.</p><a class="index-cta" href="./ai-companies.html">Explore the AI companies tracker</a><span class="home-ai-meta">{len(cs)} COMPANIES · {len(verticals)} VERTICALS · SOURCED DATA</span></div><div class="home-ai-table"><table><caption>A selection from the tracker</caption><thead><tr><th scope="col">Company</th><th scope="col">Vertical</th><th scope="col">Est. ARR / run rate</th></tr></thead><tbody>{''.join(preview)}</tbody></table><p>Dated observations, not directly comparable. Source notes and metric definitions are available in the full tracker.</p></div></section>'''
p=D/'index.html';s=p.read_text()
if '<!-- AI TRACKER PREVIEW -->' in s:s=re.sub(r'<!-- AI TRACKER PREVIEW -->.*?<!-- /AI TRACKER PREVIEW -->','<!-- AI TRACKER PREVIEW -->'+homeblock+'<!-- /AI TRACKER PREVIEW -->',s,flags=re.S)
else:s=s.replace('    <section class="section numbers-section"','<!-- AI TRACKER PREVIEW -->'+homeblock+'<!-- /AI TRACKER PREVIEW -->\n    <section class="section numbers-section"')
if './ai-tracker.css' not in s:s=s.replace('</head>','  <link rel="stylesheet" href="./ai-tracker.css">\n</head>')
p.write_text(s)
# Keep the tracker reachable from every existing page.
for p in D.glob('*.html'):
 s=p.read_text()
 def nav(m):
  n=m.group()
  if 'ai-companies.html' not in n:n=n.replace('</nav>','<a href="./ai-companies.html">AI Tracker</a></nav>')
  return n
 s=re.sub(r'<nav class="main-nav".*?</nav>',nav,s,flags=re.S)
 p.write_text(s)
print('Built tracker for',len(cs),'companies and',len(verticals),'verticals; updated homepage preview and navigation.')
