"""Build a static company ownership page from a structured editorial record.
Usage: python scripts/build-ownership.py dist/data/cursor-ownership.json
"""
import json, sys, re
from pathlib import Path
from html import escape
from urllib.parse import quote
root = Path(__file__).resolve().parents[1]
d = json.loads((root / (sys.argv[1] if len(sys.argv)>1 else 'dist/data/cursor-ownership.json')).read_text())
e=lambda x:escape(str(x),quote=True)
assert re.fullmatch(r'[a-z0-9-]+',d['slug'])
url='https://visionary-talks-editorial-concept.omerlewins.chatgpt.site/'+d['slug']+'.html'
base=(root/'dist/article.html').read_text()
header=re.search(r'<header class="site-header.*?</header>',base,re.S).group()
brief=re.search(r'<section class="page-width brief article-brief".*?</section>',base,re.S).group()
writer=re.search(r'<section class="writer-box".*?</section>',base,re.S).group()
footer='''<footer class="footer"><div class="page-width"><div class="footer-top"><div><a href="./index.html" class="footer-logo">VISIONARY TALKS</a><p>Companies. Money. Careers.</p></div><div class="footer-links"><span>About</span><span>Editorial Standards</span><span>Contact</span><span>Corrections</span><span>Advertise</span></div></div><div class="credits"><p><b>Design preview</b> Reusable ownership article with draft editorial copy and an editorial-team byline. Dated facts are linked to sources. No invented ownership percentages. Company names are typeset editorial references, not official logos. This preview is not indexed.</p></div><div class="footer-bottom"><span>© 2026 Visionary Talks</span><a href="#top">Back to top</a></div></div></footer>'''
share=f'''<div class="share-tools" aria-label="Share this article"><span>SHARE</span><a href="https://www.linkedin.com/sharing/share-offsite/?url={quote(url,safe='')}" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="https://twitter.com/intent/tweet?url={quote(url,safe='')}&amp;text={quote(d['headline'])}" target="_blank" rel="noopener noreferrer">X</a><a href="mailto:?subject={quote(d['headline'])}&amp;body={quote(url,safe='')}">Email</a><button type="button" data-copy-link>Copy link</button><span class="share-status" role="status" aria-live="polite"></span></div>'''
toc=[('article-opening','The short answer'),('ownership-map','The ownership chain'),('ownership-people','The founders'),('ownership-history','The pivotal moments'),('ownership-numbers','Funding & valuation'),('ownership-backers','The earlier investors'),('ownership-faq','Common questions'),('article-sources','Sources & method'),('author','About the writer')]
links=''.join(f'<a href="#{id}">{label}</a>' for id,label in toc)
chain=''.join(f'<li><span>{e(n["label"])}</span><b>{e(n["name"])}</b></li>' for n in d['chain'])
founders=''.join(f'<li><span>0{i}</span><h3>{e(name)}</h3><p>Co-founder</p></li>' for i,name in enumerate(d['founders'],1))
timeline=''.join(f'<li><time>{e(m["date"])}</time><div><h3>{e(m["title"])}</h3><p>{e(m["text"])} <a href="#source-{e(m["sourceId"])}" aria-label="Source for {e(m["title"])}">Source</a></p></div></li>' for m in d['milestones'])
barrows=''.join(f'<div class="ownership-bar-row"><div><b>{e(v["date"])}</b><small>{e(v["round"])}</small></div><div class="ownership-bar-track"><i style="width:{v["valueBillions"]/30*100:.2f}%"><span>${v["valueBillions"]}B</span></i></div></div>' for v in d['valuation'])
tablerows=''.join(f'<tr><th scope="row">{e(v["date"])}</th><td>{e(v["round"])}</td><td>${v["raisedBillions"]}B</td><td>${v["valueBillions"]}B</td></tr>' for v in d['valuation'])
investors=''.join(f'<span>{e(n)}</span>' for n in d['historicalInvestors'])
sources=''.join(f'<li id="source-{e(s["id"])}"><a href="{e(s["url"])}" target="_blank" rel="noopener">{e(s["label"])}</a><span>{e(s["kind"])} · {e(s["date"])}</span></li>' for s in d['sources'])
schema={'@context':'https://schema.org','@graph':[{'@type':'Article','headline':d['headline'],'description':d['dek'],'mainEntityOfPage':url,'datePublished':'2026-10-04','dateModified':d['reviewedAt'],'author':{'@type':'Organization','name':'Visionary Talks editors','url':url+'#author'},'publisher':{'@type':'Organization','name':'Visionary Talks'},'about':{'@type':'Organization','name':d['legalEntity'],'alternateName':d['brand'],'parentOrganization':{'@type':'Organization','name':d['parent']}},'articleSection':'Ownership','inLanguage':'en','creativeWorkStatus':'Draft','citation':[s['url'] for s in d['sources']]},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':url.rsplit('/',1)[0]+'/'},{'@type':'ListItem','position':2,'name':'Ownership','item':url.rsplit('/',1)[0]+'/index.html#ownership'},{'@type':'ListItem','position':3,'name':d['brand'],'item':url}]}]}
html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#ffffff"><title>{e(d['headline'])} Ownership, Founders &amp; Funding | Visionary Talks</title><meta name="description" content="{e(d['dek'])}"><meta name="robots" content="noindex,follow"><link rel="canonical" href="{url}"><meta property="og:type" content="article"><meta property="og:title" content="{e(d['headline'])}"><meta property="og:description" content="{e(d['dek'])}"><meta property="og:url" content="{url}"><meta property="og:site_name" content="Visionary Talks"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{e(d['headline'])}"><meta name="twitter:description" content="{e(d['dek'])}"><script type="application/ld+json">{json.dumps(schema)}</script><link rel="stylesheet" href="./styles.css"><link rel="stylesheet" href="./article.css"><link rel="stylesheet" href="./ownership.css"></head>
<body class="article-page ownership-page magazine-home"><a class="skip-link" href="#article-opening">Skip to article</a><div class="reading-progress" aria-hidden="true"><i id="reading-progress-fill"></i></div>{header}<main><article id="main-article">
<div class="page-width article-heading"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="./index.html">Home</a><span>/</span><a href="./index.html#ownership">Ownership</a><span>/</span><span aria-current="page">{e(d['brand'])}</span></nav>
<div class="ownership-opening"><div class="ownership-opening-copy"><div class="article-labels"><a href="./index.html#ownership" class="category">BEHIND THE BRAND</a><span class="format-label">OWNERSHIP EXPLAINED</span></div><h1>{e(d['headline'])}</h1><p class="article-dek">{e(d['dek'])}</p><div class="article-byline"><a class="byline-person" href="#author"><span class="author-monogram" aria-hidden="true">VT</span><span><b>Visionary Talks editors</b><small>Company ownership &amp; business</small></span></a><div class="article-dates"><time datetime="{d['reviewedAt']}">Updated October 4, 2026</time><span>5 min read</span></div></div>{share}<p class="ownership-preview">Design preview · source-linked example</p></div>
<aside class="company-cover" aria-label="Company snapshot"><div class="cover-top"><span>THE COMPANY FILE</span><span>001 / AI</span></div><div class="cover-name">{e(d['brand'])}<span>_</span></div><p>{e(d['legalEntity'])}</p><div class="cover-owner"><span>OWNED BY</span><b>{e(d['parent'])}</b></div><div class="cover-bottom"><span>{e(d['status'])}</span><span>AS OF OCT 2026</span></div></aside></div>
<div class="ownership-summary-strip"><div><span>PARENT COMPANY</span><b>{e(d['parent'])}</b></div><div><span>DEAL VALUE <a href="#source-deal" aria-label="Deal value source">[1]</a></span><b>{e(d['deal']['display'])}</b></div><div><span>DEAL COMPLETED</span><b>August 2026</b></div><div><span>FOUNDED</span><b>{e(d['founded'])}</b></div></div></div>
<div class="page-width article-layout"><aside class="article-index" aria-label="On this page"><div class="sticky-index"><span class="eyebrow">IN THIS COMPANY FILE</span>{links}</div></aside><div class="article-content"><details class="mobile-index"><summary>In this company file</summary>{links}</details>
<section class="quick-take" id="article-opening"><span class="category">THE SHORT ANSWER</span><h2>{e(d['parent'])}, since August 2026.</h2><p>{e(d['answer'])} <a href="#source-acquisition">Read the announcement.</a></p></section>
<p class="article-lede">A familiar product name can hide several different things: the software you use, the legal company that builds it, and the group that ultimately owns that company. Here is how those layers fit together.</p>
<section id="ownership-map" class="article-section"><span class="article-section-label">01 / FOLLOW THE OWNERSHIP</span><h2>One product. Three layers.</h2><figure class="ownership-map"><ol>{chain}</ol><figcaption>Simplified legal ownership path, read from parent to product. Intermediate operating divisions are omitted. Sources: <a href="#source-acquisition">Cursor announcement</a> and <a href="#source-reference">original reporting</a>.</figcaption></figure><p>The parent, the company, and the product are distinct. That distinction matters when reading an acquisition announcement: the transaction concerns the business behind the brand.</p></section>
<section id="ownership-people" class="article-section"><span class="article-section-label">02 / THE PEOPLE BEHIND IT</span><h2>It started with four founders.</h2><ul class="ownership-founders">{founders}</ul><p class="ownership-caption">Founding team, rather than a current leadership roster. Source: <a href="#source-reference">Visionary Talks’ original Cursor report</a>. Individual current holdings are not shown.</p><p>A founder biography explains where a business came from. It does not, by itself, establish who owns the business today. The ownership record needs its own date and supporting evidence.</p></section>
<section id="ownership-history" class="article-section"><span class="article-section-label">03 / PIVOTAL MOMENTS</span><h2>How the ownership story changed.</h2><ol class="ownership-timeline">{timeline}</ol></section>
<aside class="inarticle-ad" aria-label="Advertisement placement"><span>ADVERTISEMENT</span><div>Reserved for a sponsor message</div><small>Separate from editorial coverage</small></aside>
<section id="ownership-numbers" class="article-section"><span class="article-section-label">04 / FOLLOW THE MONEY</span><h2>The price attached to the company.</h2><figure class="ownership-chart"><div class="chart-topline"><span>DISCLOSED FUNDING VALUATIONS</span><span>USD BILLIONS</span></div><h3>$9.9B to $29.3B in two rounds.</h3><p>Company-reported valuations during 2025</p><div class="ownership-bars" role="img" aria-label="Company valuation: June 2025, 9.9 billion dollars; November 2025, 29.3 billion dollars. Zero to 30 billion dollar scale.">{barrows}<div class="ownership-bar-axis"><span>$0B</span><span>$10B</span><span>$20B</span><span>$30B</span></div></div><figcaption>Source: Cursor’s <a href="#source-series-c">Series C</a> and <a href="#source-series-d">Series D</a> announcements. The Series D valuation is explicitly post-money. These are financing snapshots, not a stock-price history.</figcaption><details class="chart-data"><summary>View the figures</summary><div class="table-scroll"><table><caption>Reported financing rounds; USD billions</caption><thead><tr><th scope="col">Date</th><th scope="col">Round</th><th scope="col">Raised</th><th scope="col">Valuation</th></tr></thead><tbody>{tablerows}</tbody></table></div></details></figure><div class="ownership-deal-note"><b>{e(d['deal']['display'])}</b><div><span>REPORTED DEAL VALUE</span><p>The later acquisition was reported as an all-stock transaction. A deal value and a funding-round valuation measure different events. <a href="#source-deal">Reuters, June 2026.</a></p></div></div><p>Funding raised is money coming into the business. Valuation is the value placed on the company in that transaction. Neither number, on its own, tells you an individual investor’s stake or voting power.</p></section>
<section id="ownership-backers" class="article-section"><span class="article-section-label">05 / BEFORE THE ACQUISITION</span><h2>The investors in the earlier chapters.</h2><div class="ownership-investors">{investors}</div><p class="ownership-caption">Selected participants named across the June and November 2025 rounds. These are historical backers, not a present-day ownership register. Sources: <a href="#source-series-c">Series C</a> / <a href="#source-series-d">Series D</a>.</p><div class="ownership-disclosure"><b>What the record does not tell us</b><p>The announcements used here do not provide a complete investor-by-investor percentage breakdown. A list of investors should not be drawn as a pie chart or treated as a ranking of control.</p></div></section>
<section id="ownership-faq" class="article-section article-faq"><span class="article-section-label">06 / COMMON QUESTIONS</span><h2>The details, clarified.</h2><details open><summary>Are Cursor and Anysphere the same thing?</summary><p>Cursor is the product and brand; Anysphere, Inc. is the company behind it. The ownership map above separates those roles.</p></details><details><summary>Is an investor always the owner of a company?</summary><p>An equity investor owns a stake. That does not automatically mean a controlling stake, a majority of votes, or ownership of the entire company.</p></details><details><summary>Does a funding valuation equal revenue?</summary><p>No. Valuation describes a transaction’s assessment of company value. Revenue describes sales over a period; annualized revenue and ARR are separate metrics that need clear definitions and dates.</p></details><details><summary>Where can I read the full original report?</summary><p><a href="https://visionarytalks.com/who-owns-cursor/">Read the original Cursor ownership story on Visionary Talks.</a> This page is a shorter example of the new company-ownership format.</p></details></section>
<section class="article-source-box ownership-sources" id="article-sources"><span class="category">SOURCES &amp; METHOD</span><h2>The record behind the story.</h2><p>Reviewed October 4, 2026. Company announcements support the transaction and financing milestones; independent reporting supports the deal value. Historical data retains its original date. This design preview uses condensed draft copy.</p><ol>{sources}</ol></section>
<nav class="article-tags" aria-label="Article topics"><span>EXPLORE THE TOPIC</span><a href="./index.html#ownership">Company ownership</a><a href="./index.html#ownership">AI companies</a><a href="./index.html#people">Founders &amp; leaders</a></nav>{writer}<div class="article-end-share"><h2>Worth sharing?</h2>{share}</div></div>
<aside class="article-facts" aria-label="Company facts"><div><span class="category">COMPANY AT A GLANCE</span><dl class="ownership-facts"><dt>Brand</dt><dd>{e(d['brand'])}</dd><dt>Legal entity</dt><dd>{e(d['legalEntity'])}</dd><dt>Parent</dt><dd>{e(d['parent'])}</dd><dt>Status</dt><dd>{e(d['status'])}</dd><dt>Sector</dt><dd>{e(d['sector'])}</dd></dl><a class="ownership-original" href="https://visionarytalks.com/who-owns-cursor/">Read the original report</a></div></aside></div></article>
<section class="page-width article-related"><div class="section-heading"><div><span class="eyebrow">MORE COMPANY FILES</span><h2>Keep following the ownership.</h2></div></div><div class="ownership-related"><a href="https://visionarytalks.com/who-owns-lovable/"><span>AI / SOFTWARE</span><b>Lovable</b><h3>Who owns Lovable?</h3><small>Read on Visionary Talks</small></a><a href="https://visionarytalks.com/who-owns-base44/"><span>AI / APP BUILDING</span><b>Base44</b><h3>Who owns Base44?</h3><small>Read on Visionary Talks</small></a><a href="./article.html"><span>BUSINESS MODEL</span><b>Apple</b><h3>What happens after the hardware sale?</h3><small>Explore the sample article</small></a></div></section>{brief}</main>{footer}<script src="./article.js"></script></body></html>'''
(root/'dist'/f'{d["slug"]}.html').write_text(html)
print('Built '+d['slug']+'.html')
